//
//  FlagIconUnicode.swift
//  CoronaVirus
//
//  Created by Manish Singh on 3/14/20.
//  Copyright © 2020 Manish Singh. All rights reserved.
//

import Foundation

extension String {
    var countryFlag: String {
        switch self {
        case "China": return "🇨🇳"
        case "Italy": return "🇮🇹"
        case "Iran": return "🇮🇷"
        case "S. Korea": return "🇰🇷"
        case "Spain": return "🇪🇸"
        case "Germany": return "🇩🇪"
        case "France": return "🇫🇷"
        case "USA": return "🇺🇸"
        case "Switzerland": return "🇨🇭"
        case "UK": return "🇬🇧"
        case "Norway": return "🇳🇴"
        case "Sweden": return "🇸🇪"
        case "Netherlands": return "🇳🇱"
        case "Denmark": return "🇩🇰"
        case "Japan": return "🇯🇵"
        case "Diamond Princess": return "🛳"
        case "Belgium": return "🇧🇪"
        case "Austria": return "🇦🇹"
        case "Qatar": return "🇶🇦"
        case "Australia": return "🇦🇺"
        case "Canada": return "🇨🇦"
        case "Malaysia": return "🇲🇾"
        case "Greece": return "🇬🇷"
        case "Finland": return "🇫🇮"
        case "Bahrain": return "🇧🇭"
        case "Singapore": return "🇸🇬"
        case "Israel": return "🇮🇱"
        case "Czechia": return "🇨🇿"
        case "Slovenia": return "🇸🇮"
        case "Portugal": return "🇵🇹"
        case "Iceland": return "🇮🇸"
        case "Brazil": return "🇧🇷"
        case "Hong Kong": return "🇭🇰"
        case "Ireland": return "🇮🇪"
        case "Romania": return "🇷🇴"
        case "Estonia": return "🇪🇪"
        case "Philippines": return "🇵🇭"
        case "Iraq": return "🇮🇶"
        case "Egypt": return "🇪🇬"
        case "Kuwait": return "🇰🇼"
        case "Poland": return "🇵🇱"
        case "Saudi Arabia": return "🇸🇦"
        case "San Marino": return "🇸🇲"
        case "India": return "🇮🇳"
        case "Indonesia": return "🇮🇩"
        case "Lebanon": return "🇱🇧"
        case "UAE": return "🇦🇪"
        case "Thailand": return "🇹🇭"
        case "Chile": return "🇨🇱"
        case "Russia": return "🇷🇺"
        case "Taiwan": return "🇹🇼"
        case "Vietnam": return "🇻🇳"
        case "Luxembourg": return "🇱🇺"
        case "Serbia": return "🇷🇸"
        case "Slovakia": return "🇸🇰"
        case "Bulgaria": return "🇧🇬"
        case "Brunei": return "🇧🇳"
        case "Albania": return "🇦🇱"
        case "Croatia": return "🇭🇷"
        case "Peru": return "🇵🇪"
        case "South Africa": return "🇿🇦"
        case "Palestine": return "🇵🇸"
        case "Algeria": return "🇩🇿"
        case "Panama": return "🇵🇦"
        case "Argentina": return "🇦🇷"
        case "Pakistan": return "🇵🇰"
        case "Georgia": return "🇬🇪"
        case "Hungary": return "🇭🇺"
        case "Ecuador": return "🇪🇨"
        case "Belarus": return "🇧🇾"
        case "Costa Rica": return "🇨🇷"
        case "Latvia": return "🇱🇻"
        case "Mexico": return "🇲🇽"
        case "Cyprus": return "🇨🇾"
        case "Colombia": return "🇨🇴"
        case "Senegal": return "🇸🇳"
        case "Oman": return "🇴🇲"
        case "Armenia": return "🇦🇲"
        case "Tunisia": return "🇹🇳"
        case "Bosnia and Herzegovina": return "🇧🇦"
        case "Malta": return "🇲🇹"
        case "Morocco": return "🇲🇦"
        case "Azerbaijan": return "🇦🇿"
        case "North Macedonia": return "🇲🇰"
        case "Moldova": return "🇲🇩"
        case "Afghanistan": return "🇦🇫"
        case "Dominican Republic": return "🇩🇴"
        case "Macao": return "🇲🇴"
        case "Sri Lanka": return "🇱🇰"
        case "Bolivia": return "🇧🇴"
        case "Maldives": return "🇲🇻"
        case "Martinique": return "🇲🇶"
        case "Faeroe Islands": return "⚐"
        case "Lithuania": return "🇱🇹"
        case "Jamaica": return "🇯🇲"
        case "Cambodia": return "🇰🇭"
        case "French Guiana": return "🇬🇫"
        case "Paraguay": return "🇵🇾"
        case "New Zealand": return "🇳🇿"
        case "Kazakhstan": return "🇰🇿"
        case "Réunion": return "🇷🇪"
        case "Turkey": return "🇹🇷"
        case "Bangladesh": return "🇧🇩"
        case "Cuba": return "🇨🇺"
        case "Liechtenstein": return "🇱🇮"
        case "Uruguay": return "🇺🇾"
        case "Ukraine": return "🇺🇦"
        case "Channel Islands": return "🇯🇪🇬🇬"
        case "French Polynesia": return "🇵🇫"
        case "Guadeloupe": return "🇬🇵"
        case "Honduras": return "🇭🇳"
        case "Puerto Rico": return "🇵🇷"
        case "Monaco": return "🇲🇨"
        case "Nigeria": return "🇳🇬"
        case "Aruba": return "🇦🇼"
        case "Burkina Faso": return "🇧🇫"
        case "Cameroon": return "🇨🇲"
        case "DRC": return "🇨🇩"
        case "Ghana": return "🇬🇭"
        case "Namibia": return "🇳🇦"
        case "Saint Martin": return "🇫🇷"
        case "Seychelles": return "🇸🇨"
        case "Trinidad and Tobago": return "🇹🇹"
        case "Venezuela": return "🇻🇪"
        case "Guyana": return "🇬🇾"
        case "Sudan": return "🇸🇩"
        case "Andorra": return "🇦🇩"
        case "Jordan": return "🇯🇴"
        case "Nepal": return "🇳🇵"
        case "Antigua and Barbuda": return "🇦🇬"
        case "Bhutan": return "🇧🇹"
        case "Cayman Islands": return "🇰🇾"
        case "Ivory Coast": return "🇨🇮"
        case "Curaçao": return "🇨🇼"
        case "Ethiopia": return "🇪🇹"
        case "Gabon": return "🇬🇦"
        case "Gibraltar": return "🇬🇮"
        case "Guatemala": return "🇬🇹"
        case "Guinea": return "🇬🇳"
        case "Vatican City": return "🇻🇦"
        case "Kenya": return "🇰🇪"
        case "Mauritania": return "🇲🇷"
        case "Mayotte": return "🇾🇹"
        case "Mongolia": return "🇲🇳"
        case "Rwanda": return "🇷🇼"
        case "St. Barth": return "🇧🇱"
        case "Saint Lucia": return "🇱🇨"
        case "St. Vincent Grenadines": return "🇻🇨"
        case "Suriname": return "🇸🇷"
        case "Eswatini": return "🇸🇿"
        case "Togo": return "🇹🇬"
        case "U.S. Virgin Islands": return "🇻🇮"
        case "Mozambique": return "🇲🇿"
        case "Uzbekistan": return "🇺🇿"
        case "Mauritius": return "🇲🇺"
        case "Montenegro": return "🇲🇪"
        case "Barbados": return "🇧🇧"
        case "Kyrgyzstan": return "🇰🇬"
        case "Tanzania": return "🇹🇿"
        case "Isle of Man": return "🇮🇲"
        case "Bahamas": return "🇧🇸"
        case "New Caledonia": return "🇳🇨"
        case "Congo": return "🇨🇩"
        case "El Salvador": return "🇸🇻"
        case "Liberia": return "🇱🇷"
        case "Madagascar": return "🇲🇬"
        case "Zambia": return "🇿🇲"
        case "Zimbabwe": return "🇿🇼"
        case "Angola": return "🇦🇴"
        case "Benin": return "🇧🇯"
        case "Bermuda": return "🇧🇲"
        case "Fiji": return "🇫🇯"
        case "Greenland": return "🇬🇱"
        case "Haiti": return "🇭🇹"
        case "Nicaragua": return "🇳🇮"
        case "Niger": return "🇳🇪"
        case "Chad": return "🇹🇩"
        case "Djibouti": return "🇩🇯"
        case "Eritrea": return "🇪🇷"
        case "Gambia": return "🇬🇲"
        case "Montserrat": return "🇲🇸"
        case "Papua New Guinea": return "🇵🇬"
        case "Sint Maarten": return "🇸🇽"
        case "Somalia": return "🇸🇴"
        case "Timor-Leste": return "🇹🇱"
        case "Uganda": return "🇺🇬"
        case "Guam": return "🇬🇺"
        case "Equatorial Guinea": return "🇬🇶"

        default:
            print(self)
            return "🏳"
        }
    }
}


